-- Asset Control database schema for Supabase/Postgres
-- Generated from outputs/database/asset-control-database.json

create table if not exists public.asset_control_metadata (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.master_companies (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_departments (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_locations (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_types (
  code text primary key,
  name text not null,
  group_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_type_groups (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_statuses (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.computer_assets (
  id bigint generated by default as identity primary key,
  asset_code text not null unique,
  rust_desk_id text,
  company text,
  type text,
  brand text,
  model text,
  serial text,
  assigned_user text,
  department text,
  location text,
  room text,
  purchase_date text,
  status text,
  warranty_expiration_date text,
  windows_version text,
  sent_for_repair_date text,
  adapter boolean not null default false,
  mouse boolean not null default false,
  laptop_bag boolean not null default false,
  sync_one_drive boolean not null default false,
  remark text,
  image_url text,
  source_sheet text,
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.other_assets (
  id bigint generated by default as identity primary key,
  asset_code text not null unique,
  company text,
  type text,
  brand text,
  model text,
  serial text,
  location text,
  room text,
  purchase_date text,
  status text,
  warranty_expiration_date text,
  remark text,
  image_url text,
  source_sheet text,
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_history (
  id bigint generated by default as identity primary key,
  title text,
  asset text,
  type text,
  date text,
  completed_date text,
  cost text,
  status text,
  operator text,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  asset text,
  brand text,
  type text,
  requester text,
  date text,
  priority text,
  status text,
  approved_date text,
  approval_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.checkout_records (
  id bigint generated by default as identity primary key,
  asset text,
  subtitle text,
  requester text,
  department text,
  date text,
  expected_return text,
  returned_date text,
  purpose text,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  notification_key text unique,
  title text,
  body text,
  category text,
  date text,
  read boolean not null default false,
  tone text,
  type text,
  remaining_days integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.login_history (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  time text,
  ip text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text unique,
  password text,
  name text,
  department text,
  role text not null default 'user',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_asset_control_metadata_updated_at on public.asset_control_metadata;
create trigger set_asset_control_metadata_updated_at before update on public.asset_control_metadata
for each row execute function public.set_updated_at();

drop trigger if exists set_master_companies_updated_at on public.master_companies;
create trigger set_master_companies_updated_at before update on public.master_companies
for each row execute function public.set_updated_at();

drop trigger if exists set_master_departments_updated_at on public.master_departments;
create trigger set_master_departments_updated_at before update on public.master_departments
for each row execute function public.set_updated_at();

drop trigger if exists set_master_locations_updated_at on public.master_locations;
create trigger set_master_locations_updated_at before update on public.master_locations
for each row execute function public.set_updated_at();

drop trigger if exists set_master_types_updated_at on public.master_types;
create trigger set_master_types_updated_at before update on public.master_types
for each row execute function public.set_updated_at();

drop trigger if exists set_computer_assets_updated_at on public.computer_assets;
create trigger set_computer_assets_updated_at before update on public.computer_assets
for each row execute function public.set_updated_at();

drop trigger if exists set_other_assets_updated_at on public.other_assets;
create trigger set_other_assets_updated_at before update on public.other_assets
for each row execute function public.set_updated_at();

drop trigger if exists set_maintenance_history_updated_at on public.maintenance_history;
create trigger set_maintenance_history_updated_at before update on public.maintenance_history
for each row execute function public.set_updated_at();

drop trigger if exists set_maintenance_requests_updated_at on public.maintenance_requests;
create trigger set_maintenance_requests_updated_at before update on public.maintenance_requests
for each row execute function public.set_updated_at();

drop trigger if exists set_checkout_records_updated_at on public.checkout_records;
create trigger set_checkout_records_updated_at before update on public.checkout_records
for each row execute function public.set_updated_at();

drop trigger if exists set_notifications_updated_at on public.notifications;
create trigger set_notifications_updated_at before update on public.notifications
for each row execute function public.set_updated_at();

drop trigger if exists set_app_users_updated_at on public.app_users;
create trigger set_app_users_updated_at before update on public.app_users
for each row execute function public.set_updated_at();

alter table public.asset_control_metadata enable row level security;
drop policy if exists "asset_control_metadata_authenticated_select" on public.asset_control_metadata;
drop policy if exists "asset_control_metadata_authenticated_insert" on public.asset_control_metadata;
drop policy if exists "asset_control_metadata_authenticated_update" on public.asset_control_metadata;
drop policy if exists "asset_control_metadata_authenticated_delete" on public.asset_control_metadata;
create policy "asset_control_metadata_authenticated_select" on public.asset_control_metadata for select to authenticated using (true);
create policy "asset_control_metadata_authenticated_insert" on public.asset_control_metadata for insert to authenticated with check (true);
create policy "asset_control_metadata_authenticated_update" on public.asset_control_metadata for update to authenticated using (true) with check (true);
create policy "asset_control_metadata_authenticated_delete" on public.asset_control_metadata for delete to authenticated using (true);
alter table public.master_companies enable row level security;
drop policy if exists "master_companies_authenticated_select" on public.master_companies;
drop policy if exists "master_companies_authenticated_insert" on public.master_companies;
drop policy if exists "master_companies_authenticated_update" on public.master_companies;
drop policy if exists "master_companies_authenticated_delete" on public.master_companies;
create policy "master_companies_authenticated_select" on public.master_companies for select to authenticated using (true);
create policy "master_companies_authenticated_insert" on public.master_companies for insert to authenticated with check (true);
create policy "master_companies_authenticated_update" on public.master_companies for update to authenticated using (true) with check (true);
create policy "master_companies_authenticated_delete" on public.master_companies for delete to authenticated using (true);
alter table public.master_departments enable row level security;
drop policy if exists "master_departments_authenticated_select" on public.master_departments;
drop policy if exists "master_departments_authenticated_insert" on public.master_departments;
drop policy if exists "master_departments_authenticated_update" on public.master_departments;
drop policy if exists "master_departments_authenticated_delete" on public.master_departments;
create policy "master_departments_authenticated_select" on public.master_departments for select to authenticated using (true);
create policy "master_departments_authenticated_insert" on public.master_departments for insert to authenticated with check (true);
create policy "master_departments_authenticated_update" on public.master_departments for update to authenticated using (true) with check (true);
create policy "master_departments_authenticated_delete" on public.master_departments for delete to authenticated using (true);
alter table public.master_locations enable row level security;
drop policy if exists "master_locations_authenticated_select" on public.master_locations;
drop policy if exists "master_locations_authenticated_insert" on public.master_locations;
drop policy if exists "master_locations_authenticated_update" on public.master_locations;
drop policy if exists "master_locations_authenticated_delete" on public.master_locations;
create policy "master_locations_authenticated_select" on public.master_locations for select to authenticated using (true);
create policy "master_locations_authenticated_insert" on public.master_locations for insert to authenticated with check (true);
create policy "master_locations_authenticated_update" on public.master_locations for update to authenticated using (true) with check (true);
create policy "master_locations_authenticated_delete" on public.master_locations for delete to authenticated using (true);
alter table public.master_types enable row level security;
drop policy if exists "master_types_authenticated_select" on public.master_types;
drop policy if exists "master_types_authenticated_insert" on public.master_types;
drop policy if exists "master_types_authenticated_update" on public.master_types;
drop policy if exists "master_types_authenticated_delete" on public.master_types;
create policy "master_types_authenticated_select" on public.master_types for select to authenticated using (true);
create policy "master_types_authenticated_insert" on public.master_types for insert to authenticated with check (true);
create policy "master_types_authenticated_update" on public.master_types for update to authenticated using (true) with check (true);
create policy "master_types_authenticated_delete" on public.master_types for delete to authenticated using (true);
alter table public.computer_assets enable row level security;
drop policy if exists "computer_assets_authenticated_select" on public.computer_assets;
drop policy if exists "computer_assets_authenticated_insert" on public.computer_assets;
drop policy if exists "computer_assets_authenticated_update" on public.computer_assets;
drop policy if exists "computer_assets_authenticated_delete" on public.computer_assets;
create policy "computer_assets_authenticated_select" on public.computer_assets for select to authenticated using (true);
create policy "computer_assets_authenticated_insert" on public.computer_assets for insert to authenticated with check (true);
create policy "computer_assets_authenticated_update" on public.computer_assets for update to authenticated using (true) with check (true);
create policy "computer_assets_authenticated_delete" on public.computer_assets for delete to authenticated using (true);
alter table public.other_assets enable row level security;
drop policy if exists "other_assets_authenticated_select" on public.other_assets;
drop policy if exists "other_assets_authenticated_insert" on public.other_assets;
drop policy if exists "other_assets_authenticated_update" on public.other_assets;
drop policy if exists "other_assets_authenticated_delete" on public.other_assets;
create policy "other_assets_authenticated_select" on public.other_assets for select to authenticated using (true);
create policy "other_assets_authenticated_insert" on public.other_assets for insert to authenticated with check (true);
create policy "other_assets_authenticated_update" on public.other_assets for update to authenticated using (true) with check (true);
create policy "other_assets_authenticated_delete" on public.other_assets for delete to authenticated using (true);
alter table public.maintenance_history enable row level security;
drop policy if exists "maintenance_history_authenticated_select" on public.maintenance_history;
drop policy if exists "maintenance_history_authenticated_insert" on public.maintenance_history;
drop policy if exists "maintenance_history_authenticated_update" on public.maintenance_history;
drop policy if exists "maintenance_history_authenticated_delete" on public.maintenance_history;
create policy "maintenance_history_authenticated_select" on public.maintenance_history for select to authenticated using (true);
create policy "maintenance_history_authenticated_insert" on public.maintenance_history for insert to authenticated with check (true);
create policy "maintenance_history_authenticated_update" on public.maintenance_history for update to authenticated using (true) with check (true);
create policy "maintenance_history_authenticated_delete" on public.maintenance_history for delete to authenticated using (true);
alter table public.maintenance_requests enable row level security;
drop policy if exists "maintenance_requests_authenticated_select" on public.maintenance_requests;
drop policy if exists "maintenance_requests_authenticated_insert" on public.maintenance_requests;
drop policy if exists "maintenance_requests_authenticated_update" on public.maintenance_requests;
drop policy if exists "maintenance_requests_authenticated_delete" on public.maintenance_requests;
create policy "maintenance_requests_authenticated_select" on public.maintenance_requests for select to authenticated using (true);
create policy "maintenance_requests_authenticated_insert" on public.maintenance_requests for insert to authenticated with check (true);
create policy "maintenance_requests_authenticated_update" on public.maintenance_requests for update to authenticated using (true) with check (true);
create policy "maintenance_requests_authenticated_delete" on public.maintenance_requests for delete to authenticated using (true);
alter table public.checkout_records enable row level security;
drop policy if exists "checkout_records_authenticated_select" on public.checkout_records;
drop policy if exists "checkout_records_authenticated_insert" on public.checkout_records;
drop policy if exists "checkout_records_authenticated_update" on public.checkout_records;
drop policy if exists "checkout_records_authenticated_delete" on public.checkout_records;
create policy "checkout_records_authenticated_select" on public.checkout_records for select to authenticated using (true);
create policy "checkout_records_authenticated_insert" on public.checkout_records for insert to authenticated with check (true);
create policy "checkout_records_authenticated_update" on public.checkout_records for update to authenticated using (true) with check (true);
create policy "checkout_records_authenticated_delete" on public.checkout_records for delete to authenticated using (true);
alter table public.notifications enable row level security;
drop policy if exists "notifications_authenticated_select" on public.notifications;
drop policy if exists "notifications_authenticated_insert" on public.notifications;
drop policy if exists "notifications_authenticated_update" on public.notifications;
drop policy if exists "notifications_authenticated_delete" on public.notifications;
create policy "notifications_authenticated_select" on public.notifications for select to authenticated using (true);
create policy "notifications_authenticated_insert" on public.notifications for insert to authenticated with check (true);
create policy "notifications_authenticated_update" on public.notifications for update to authenticated using (true) with check (true);
create policy "notifications_authenticated_delete" on public.notifications for delete to authenticated using (true);
alter table public.login_history enable row level security;
drop policy if exists "login_history_authenticated_select" on public.login_history;
drop policy if exists "login_history_authenticated_insert" on public.login_history;
drop policy if exists "login_history_authenticated_update" on public.login_history;
drop policy if exists "login_history_authenticated_delete" on public.login_history;
create policy "login_history_authenticated_select" on public.login_history for select to authenticated using (true);
create policy "login_history_authenticated_insert" on public.login_history for insert to authenticated with check (true);
create policy "login_history_authenticated_update" on public.login_history for update to authenticated using (true) with check (true);
create policy "login_history_authenticated_delete" on public.login_history for delete to authenticated using (true);
alter table public.app_users enable row level security;
drop policy if exists "app_users_authenticated_select" on public.app_users;
drop policy if exists "app_users_authenticated_insert" on public.app_users;
drop policy if exists "app_users_authenticated_update" on public.app_users;
drop policy if exists "app_users_authenticated_delete" on public.app_users;
create policy "app_users_authenticated_select" on public.app_users for select to authenticated using (true);
create policy "app_users_authenticated_insert" on public.app_users for insert to authenticated with check (true);
create policy "app_users_authenticated_update" on public.app_users for update to authenticated using (true) with check (true);
create policy "app_users_authenticated_delete" on public.app_users for delete to authenticated using (true);

