from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / "outputs" / "database" / "asset-control-database.json"
OUT_DIR = ROOT / "outputs" / "supabase"


TABLES = [
    "asset_control_metadata",
    "master_companies",
    "master_departments",
    "master_locations",
    "master_types",
    "computer_assets",
    "other_assets",
    "maintenance_history",
    "maintenance_requests",
    "checkout_records",
    "notifications",
    "login_history",
    "app_users",
]


def sql(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def insert_statement(table, rows, columns, conflict=None):
    if not rows:
        return f"-- {table}: no rows to seed\n"
    values = []
    for row in rows:
        values.append("(" + ", ".join(sql(row.get(column)) for column in columns) + ")")
    conflict_sql = f"\n{conflict}" if conflict else ""
    return (
        f"insert into public.{table} ({', '.join(columns)}) values\n"
        + ",\n".join(values)
        + conflict_sql
        + ";\n"
    )


def build_schema():
    policies = []
    for table in TABLES:
        policies.append(
            f"""alter table public.{table} enable row level security;
drop policy if exists "{table}_authenticated_select" on public.{table};
drop policy if exists "{table}_authenticated_insert" on public.{table};
drop policy if exists "{table}_authenticated_update" on public.{table};
drop policy if exists "{table}_authenticated_delete" on public.{table};
create policy "{table}_authenticated_select" on public.{table} for select to authenticated using (true);
create policy "{table}_authenticated_insert" on public.{table} for insert to authenticated with check (true);
create policy "{table}_authenticated_update" on public.{table} for update to authenticated using (true) with check (true);
create policy "{table}_authenticated_delete" on public.{table} for delete to authenticated using (true);
"""
        )

    return f"""-- Asset Control database schema for Supabase/Postgres
-- Generated from outputs/database/asset-control-database.json

create table if not exists public.asset_control_metadata (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.master_companies (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_departments (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_locations (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_types (
  code text primary key,
  name text not null,
  group_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_type_groups (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.master_statuses (
  code text primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.computer_assets (
  id bigint generated by default as identity primary key,
  asset_code text not null unique,
  rust_desk_id text,
  company text,
  type text,
  brand text,
  model text,
  serial text,
  assigned_user text,
  department text,
  location text,
  room text,
  purchase_date text,
  status text,
  warranty_expiration_date text,
  windows_version text,
  sent_for_repair_date text,
  adapter boolean not null default false,
  mouse boolean not null default false,
  laptop_bag boolean not null default false,
  sync_one_drive boolean not null default false,
  remark text,
  image_url text,
  source_sheet text,
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.other_assets (
  id bigint generated by default as identity primary key,
  asset_code text not null unique,
  company text,
  type text,
  brand text,
  model text,
  serial text,
  location text,
  room text,
  purchase_date text,
  status text,
  warranty_expiration_date text,
  remark text,
  image_url text,
  source_sheet text,
  source_row integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_history (
  id bigint generated by default as identity primary key,
  title text,
  asset text,
  type text,
  date text,
  completed_date text,
  cost text,
  status text,
  operator text,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  asset text,
  brand text,
  type text,
  requester text,
  date text,
  priority text,
  status text,
  approved_date text,
  approval_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.checkout_records (
  id bigint generated by default as identity primary key,
  asset text,
  subtitle text,
  requester text,
  department text,
  date text,
  expected_return text,
  returned_date text,
  purpose text,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  notification_key text unique,
  title text,
  body text,
  category text,
  date text,
  read boolean not null default false,
  tone text,
  type text,
  remaining_days integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.login_history (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  time text,
  ip text,
  status text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text unique,
  password text,
  name text,
  department text,
  role text not null default 'user',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_asset_control_metadata_updated_at on public.asset_control_metadata;
create trigger set_asset_control_metadata_updated_at before update on public.asset_control_metadata
for each row execute function public.set_updated_at();

drop trigger if exists set_master_companies_updated_at on public.master_companies;
create trigger set_master_companies_updated_at before update on public.master_companies
for each row execute function public.set_updated_at();

drop trigger if exists set_master_departments_updated_at on public.master_departments;
create trigger set_master_departments_updated_at before update on public.master_departments
for each row execute function public.set_updated_at();

drop trigger if exists set_master_locations_updated_at on public.master_locations;
create trigger set_master_locations_updated_at before update on public.master_locations
for each row execute function public.set_updated_at();

drop trigger if exists set_master_types_updated_at on public.master_types;
create trigger set_master_types_updated_at before update on public.master_types
for each row execute function public.set_updated_at();

drop trigger if exists set_computer_assets_updated_at on public.computer_assets;
create trigger set_computer_assets_updated_at before update on public.computer_assets
for each row execute function public.set_updated_at();

drop trigger if exists set_other_assets_updated_at on public.other_assets;
create trigger set_other_assets_updated_at before update on public.other_assets
for each row execute function public.set_updated_at();

drop trigger if exists set_maintenance_history_updated_at on public.maintenance_history;
create trigger set_maintenance_history_updated_at before update on public.maintenance_history
for each row execute function public.set_updated_at();

drop trigger if exists set_maintenance_requests_updated_at on public.maintenance_requests;
create trigger set_maintenance_requests_updated_at before update on public.maintenance_requests
for each row execute function public.set_updated_at();

drop trigger if exists set_checkout_records_updated_at on public.checkout_records;
create trigger set_checkout_records_updated_at before update on public.checkout_records
for each row execute function public.set_updated_at();

drop trigger if exists set_notifications_updated_at on public.notifications;
create trigger set_notifications_updated_at before update on public.notifications
for each row execute function public.set_updated_at();

drop trigger if exists set_app_users_updated_at on public.app_users;
create trigger set_app_users_updated_at before update on public.app_users
for each row execute function public.set_updated_at();

{"".join(policies)}
"""


def build_seed(data):
    statements = []
    statements.append("-- Asset Control seed data generated from current app database\n")
    statements.append("begin;\n")
    statements.append(
        "truncate table public.login_history, public.notifications, public.checkout_records, "
        "public.maintenance_requests, public.maintenance_history, public.other_assets, "
        "public.computer_assets, public.master_types, public.master_locations, "
        "public.master_departments, public.master_companies, public.asset_control_metadata, "
        "public.app_users restart identity cascade;\n"
    )

    statements.append(insert_statement("asset_control_metadata", [
        {"key": "sourceFile", "value": data.get("sourceFile", "")},
        {"key": "sourceId", "value": data.get("sourceId", "")},
        {"key": "generatedAt", "value": data.get("generatedAt", "")},
    ], ["key", "value"]))

    master = data.get("master", {})
    for table, key in [
        ("master_companies", "companies"),
        ("master_departments", "departments"),
        ("master_locations", "locations"),
        ("master_types", "types"),
    ]:
        statements.append(insert_statement(table, master.get(key, []), ["code", "name"]))

    statements.append(insert_statement("computer_assets", [
        {
            "asset_code": row.get("assetCode"),
            "rust_desk_id": row.get("rustDeskId"),
            "company": row.get("company"),
            "type": row.get("type"),
            "brand": row.get("brand"),
            "model": row.get("model"),
            "serial": row.get("serial"),
            "assigned_user": row.get("user"),
            "department": row.get("department"),
            "location": row.get("location"),
            "room": row.get("room"),
            "purchase_date": row.get("purchaseDate"),
            "status": row.get("status"),
            "warranty_expiration_date": row.get("warrantyExpirationDate"),
            "windows_version": row.get("windowsVersion"),
            "sent_for_repair_date": row.get("sentForRepairDate"),
            "adapter": row.get("adapter"),
            "mouse": row.get("mouse"),
            "laptop_bag": row.get("laptopBag"),
            "sync_one_drive": row.get("syncOneDrive"),
            "remark": row.get("remark"),
            "image_url": row.get("imageUrl"),
            "source_sheet": row.get("sourceSheet"),
            "source_row": row.get("sourceRow"),
        }
        for row in data.get("computerAssets", [])
    ], [
        "asset_code", "rust_desk_id", "company", "type", "brand", "model", "serial",
        "assigned_user", "department", "location", "room", "purchase_date", "status",
        "warranty_expiration_date", "windows_version", "sent_for_repair_date", "adapter",
        "mouse", "laptop_bag", "sync_one_drive", "remark", "image_url", "source_sheet", "source_row",
    ]))

    statements.append(insert_statement("other_assets", [
        {
            "asset_code": row.get("assetCode"),
            "company": row.get("company"),
            "type": row.get("type"),
            "brand": row.get("brand"),
            "model": row.get("model"),
            "serial": row.get("serial"),
            "location": row.get("location"),
            "room": row.get("room"),
            "purchase_date": row.get("purchaseDate"),
            "status": row.get("status"),
            "warranty_expiration_date": row.get("warrantyExpirationDate"),
            "remark": row.get("remark"),
            "image_url": row.get("imageUrl"),
            "source_sheet": row.get("sourceSheet"),
            "source_row": row.get("sourceRow"),
        }
        for row in data.get("otherAssets", [])
    ], [
        "asset_code", "company", "type", "brand", "model", "serial", "location", "room",
        "purchase_date", "status", "warranty_expiration_date", "remark", "image_url", "source_sheet", "source_row",
    ]))

    statements.append(insert_statement("maintenance_history", [
        {
            "title": row.get("title"),
            "asset": row.get("asset"),
            "type": row.get("type"),
            "date": row.get("date"),
            "completed_date": row.get("completedDate"),
            "cost": row.get("cost"),
            "status": row.get("status"),
            "operator": row.get("operator"),
            "details": row.get("details"),
        }
        for row in data.get("maintenanceHistory", [])
    ], ["title", "asset", "type", "date", "completed_date", "cost", "status", "operator", "details"]))

    statements.append(insert_statement("maintenance_requests", [
        {
            "title": row.get("title"),
            "description": row.get("desc") or row.get("description"),
            "asset": row.get("asset"),
            "brand": row.get("brand"),
            "type": row.get("type"),
            "requester": row.get("requester"),
            "date": row.get("date"),
            "priority": row.get("priority"),
            "status": row.get("status"),
            "approved_date": row.get("approvedDate"),
            "approval_note": row.get("approvalNote"),
        }
        for row in data.get("maintenanceRequests", [])
    ], [
        "title", "description", "asset", "brand", "type", "requester", "date",
        "priority", "status", "approved_date", "approval_note",
    ]))

    statements.append(insert_statement("checkout_records", [
        {
            "asset": row.get("asset"),
            "subtitle": row.get("sub"),
            "requester": row.get("requester"),
            "department": row.get("department"),
            "date": row.get("date"),
            "expected_return": row.get("expectedReturn"),
            "returned_date": row.get("returnedDate"),
            "purpose": row.get("purpose"),
            "status": row.get("status"),
        }
        for row in data.get("checkoutRecords", [])
    ], [
        "asset", "subtitle", "requester", "department", "date", "expected_return",
        "returned_date", "purpose", "status",
    ]))

    statements.append(insert_statement("notifications", [
        {
            "notification_key": row.get("key"),
            "title": row.get("title"),
            "body": row.get("body"),
            "category": row.get("category"),
            "date": row.get("date"),
            "read": row.get("read", False),
            "tone": row.get("tone"),
            "type": row.get("type"),
            "remaining_days": row.get("remainingDays"),
        }
        for row in data.get("notifications", [])
    ], [
        "notification_key", "title", "body", "category", "date", "read",
        "tone", "type", "remaining_days",
    ]))

    statements.append(insert_statement("login_history", data.get("loginHistory", []), [
        "name", "role", "time", "ip", "status",
    ]))

    statements.append(insert_statement("app_users", data.get("users", []), [
        "username", "email", "password", "name", "department", "role", "active",
    ]))

    statements.append("commit;\n")
    return "\n".join(statements)


def main():
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    schema = build_schema()
    seed = build_seed(data)
    (OUT_DIR / "asset-control-schema.sql").write_text(schema, encoding="utf-8")
    (OUT_DIR / "asset-control-seed.sql").write_text(seed, encoding="utf-8")
    (OUT_DIR / "asset-control-full.sql").write_text(schema + "\n" + seed, encoding="utf-8")
    summary = {
        "schema": str(OUT_DIR / "asset-control-schema.sql"),
        "seed": str(OUT_DIR / "asset-control-seed.sql"),
        "full": str(OUT_DIR / "asset-control-full.sql"),
        "computerAssets": len(data.get("computerAssets", [])),
        "otherAssets": len(data.get("otherAssets", [])),
        "maintenanceHistory": len(data.get("maintenanceHistory", [])),
        "maintenanceRequests": len(data.get("maintenanceRequests", [])),
        "checkoutRecords": len(data.get("checkoutRecords", [])),
        "users": len(data.get("users", [])),
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
